// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://espqykyyqpyxtehzaaxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzcHF5a3l5cXB5eHRlaHphYXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjM3MDIsImV4cCI6MjA3Mjc5OTcwMn0.nBlK_WvQ7USCaIgTNz_VroUE7hKt6QqBwcykUY0V0mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});